import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { StatusReport, InspectionLabel } from '@/types';

export async function generateStatusReportPDF(report: StatusReport): Promise<void> {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPosition = 15;
  const lineHeight = 7;
  const margin = 10;
  const contentWidth = pageWidth - 2 * margin;

  // Helper function to add a new page if needed
  const checkPageBreak = (requiredSpace: number) => {
    if (yPosition + requiredSpace > pageHeight - 10) {
      doc.addPage();
      yPosition = 15;
    }
  };

  // Header
  doc.setFontSize(20);
  doc.text('360° Vehicle Inspection Report', margin, yPosition);
  yPosition += lineHeight + 3;

  // Report ID
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Report ID: ${report.id}`, margin, yPosition);
  yPosition += lineHeight;

  // Vehicle Information
  checkPageBreak(30);
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.text('Vehicle Information', margin, yPosition);
  yPosition += lineHeight;

  doc.setFontSize(10);
  doc.text(`License Plate: ${report.vehicle_info.license_plate}`, margin + 5, yPosition);
  yPosition += lineHeight;
  doc.text(`Customer: ${report.vehicle_info.customer_name}`, margin + 5, yPosition);
  yPosition += lineHeight;
  doc.text(`Odometer: ${report.vehicle_info.odometer} km`, margin + 5, yPosition);
  yPosition += lineHeight;

  // Summary
  checkPageBreak(40);
  doc.setFontSize(12);
  doc.text('Inspection Summary', margin, yPosition);
  yPosition += lineHeight;

  doc.setFontSize(10);
  const summaryData = [
    [`Total Issues Found: ${report.summary.total_issues}`, 'left'],
    [`[PASS] Pass: ${report.summary.pass_count}`, 'left'],
    [`[WARN] Warning: ${report.summary.warning_count}`, 'left'],
    [`[FAIL] Fail: ${report.summary.fail_count}`, 'left'],
  ];

  summaryData.forEach(([text]) => {
    doc.text(text, margin + 5, yPosition);
    yPosition += lineHeight;
  });

  // Detailed Findings
  checkPageBreak(50);
  doc.setFontSize(12);
  doc.text('Detailed Findings', margin, yPosition);
  yPosition += lineHeight + 2;

  doc.setFontSize(9);
  doc.setTextColor(50, 50, 50);

  report.labels.forEach((label, index) => {
    checkPageBreak(25);

    // Issue number and text
    doc.setTextColor(0, 0, 0);
    const issueText = `${index + 1}. [${label.angle.toUpperCase()}] ${label.text}`;
    const wrappedIssue = doc.splitTextToSize(issueText, contentWidth - 10);
    doc.text(wrappedIssue, margin + 5, yPosition);
    yPosition += wrappedIssue.length * (lineHeight - 1) + 2;

    // Severity badge
    doc.setTextColor(100, 100, 100);
    const severityText = `Severity: ${label.severity?.toUpperCase() || 'UNSPECIFIED'}`;
    doc.text(severityText, margin + 5, yPosition);
    yPosition += lineHeight;

    // Additional data if exists
    if (label.data && Object.keys(label.data).length > 0) {
      doc.setFontSize(8);
      doc.setTextColor(120, 120, 120);
      Object.entries(label.data).forEach(([key, value]) => {
        if (value !== null && value !== undefined) {
          const dataLine = `${key.charAt(0).toUpperCase() + key.slice(1)}: ${value}`;
          doc.text(dataLine, margin + 8, yPosition);
          yPosition += lineHeight - 1;
        }
      });
      doc.setFontSize(9);
    }

    yPosition += lineHeight;
  });

  // Footer
  checkPageBreak(15);
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  const generatedDate = new Date(report.generated_at).toLocaleDateString();
  doc.text(`Generated on: ${generatedDate}`, margin, pageHeight - 10);
  doc.text('This is an automated report generated by the 360° Inspection System', margin, pageHeight - 5);

  // Save the PDF
  doc.save(`inspection_report_${report.id}.pdf`);
}

export async function generateHTMLReportPDF(
  htmlElement: HTMLElement,
  fileName: string = 'inspection_report'
): Promise<void> {
  try {
    const canvas = await html2canvas(htmlElement, {
      scale: 2,
      useCORS: true,
      allowTaint: true,
    });

    const imgData = canvas.toDataURL('image/png');
    const doc = new jsPDF('p', 'mm', 'a4');
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const imgWidth = pageWidth - 20;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    let heightLeft = imgHeight;
    let position = 0;

    doc.addImage(imgData, 'PNG', 10, position + 10, imgWidth, imgHeight);
    heightLeft -= pageHeight;

    while (heightLeft >= 0) {
      position = heightLeft - imgHeight;
      doc.addPage();
      doc.addImage(imgData, 'PNG', 10, position + 10, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    doc.save(`${fileName}_${Date.now()}.pdf`);
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw error;
  }
}

export function generateSummaryStats(labels: InspectionLabel[]) {
  return {
    total_issues: labels.length,
    pass_count: labels.filter(l => l.severity === 'pass').length,
    warning_count: labels.filter(l => l.severity === 'warning').length,
    fail_count: labels.filter(l => l.severity === 'fail').length,
  };
}
